locations = ['europe','australia','south america','north america','africa']
print (locations)
print (sorted(locations))
print (locations)
print (sorted(locations,reverse=True))
print (locations)
locations.reverse()
print (locations)
locations.reverse()
print (locations)
locations.sort()
print (locations)
locations.sort(reverse=True)
print (locations)
